-- generated from http://petopia.brashendeavors.net/html/browse/search_advanced.php?q=1&innate_skills=Any&tameable=1&page_size=500
-- Fri Jun 20 2008 17:49:47 GMT-0700 (PDT)

-- t=1: elite
-- t=2: rare
-- t=3: rare + elite

FHH_BeastInfo = {
["Agam'ar"]                    	= {f=FHH_BOAR,        	z="Razorfen Kraul",           	min=24,	max=25,	t=1,	charge=3,	},
["Aku'mai Fisher"]             	= {f=FHH_TURTLE,      	z="Blackfathom Deeps",        	min=22,	max=23,	t=1,	bite=3,	shell=1,	},
["Aku'mai Snapjaw"]            	= {f=FHH_TURTLE,      	z="Blackfathom Deeps",        	min=23,			t=1,	bite=4,	shell=1,	},
["Angerclaw Mauler"]           	= {f=FHH_BEAR,        	z="Felwood",                  	min=49,	max=50,			claw=7,	},
["Arash-ethis"]                	= {f=FHH_WIND_SERPENT,	z="Feralas",                  	min=49,			t=2,	dive=2,	lightning=5,	},
["Ashenvale Bear"]             	= {f=FHH_BEAR,        	z="Ashenvale",                	min=21,	max=22,			claw=3,	},
["Ashmane Boar"]               	= {f=FHH_BOAR,        	z="Blasted Lands",            	min=48,	max=49,			charge=5,},
["Barbed Crustacean"]          	= {f=FHH_CRAB,        	z="Blackfathom Deeps",        	min=23,			t=1,	claw=4,	},
["Barnabus"]                   	= {f=FHH_WOLF,        	z="Badlands",                 	min=38,			t=2,	bite=5,	},
["Battleboar"]                 	= {f=FHH_BOAR,        	z="Mulgore",                  	min=3,	max=4,			charge=1,},
["Bellygrub"]                  	= {f=FHH_BOAR,        	z="Redridge Mountains",       	min=24,					charge=3,},
["Besseleth"]                  	= {f=FHH_SPIDER,      	z="Stonetalon Mountains",     	min=21,					bite=3,	},
["Bhag'thera"]                 	= {f=FHH_CAT,         	z="Stranglethorn Vale",       	min=40,					dash=2,	},
["Bjarn"]                      	= {f=FHH_BEAR,        	z="Dun Morogh",               	min=12,			t=2,	claw=2,	},
["Black Bear Patriarch"]       	= {f=FHH_BEAR,        	z="Loch Modan",               	min=16,	max=17,			claw=3,	},
["Black Ravager"]              	= {f=FHH_WOLF,        	z="Duskwood",                 	min=24,	max=25,			bite=4,	},
["Black Ravager Mastiff"]      	= {f=FHH_WOLF,        	z="Duskwood",                 	min=25,	max=26,			bite=4,	howl=2,	},
["Blackrock Worg"]             	= {f=FHH_WOLF,        	z="Burning Steppes",          	min=54,	max=55,			dash=3,	},
["Blackwind Warp Chaser"]      	= {f=FHH_WARP_STALKER,	z="Terokkar Forest",          	min=69,	max=70,			warp=1,	},
["Blind Hunter"]               	= {f=FHH_BAT,         	z="Razorfen Kraul",           	min=27,			t=3,	cower=3,	dive=1,	},
["Blisterpaw Hyena"]           	= {f=FHH_HYENA,       	z="Tanaris",                  	min=44,	max=45,			dash=2,	},
["Bloodaxe Worg"]              	= {f=FHH_WOLF,        	z="Blackrock Spire",          	min=56,	max=57,			bite=8,	dash=3,	howl=4,	},
["Bloodfalcon"]                	= {f=FHH_DRAGONHAWK,  	z="The Botanica",             	min=69,	max=70,	t=1,	firebreath=2,	},
["Bloodmaul Battle Worg"]      	= {f=FHH_WOLF,        	z="Blade's Edge Mountains",   	min=66,	max=67,			howl=4,	},
["Bloodmaul Dire Wolf"]        	= {f=FHH_WOLF,        	z="Blade's Edge Mountains",   	min=65,					howl=4,	},
["Bloodsnout Worg"]            	= {f=FHH_WOLF,        	z="Silverpine Forest",        	min=16,	max=17,			bite=3,	},
["Bonepaw Hyena"]              	= {f=FHH_HYENA,       	z="Desolace",                 	min=33,	max=35,			dash=1,	},
["Bristleback Battleboar"]     	= {f=FHH_BOAR,        	z="Mulgore",                  	min=4,	max=5,			charge=1,},
["Broken Tooth"]               	= {f=FHH_CAT,         	z="Badlands",                 	min=37,			t=2,	dash=1,	},
["Carrion Vulture"]            	= {f=FHH_CARRION_BIRD,	z="Western Plaguelands",      	min=50,	max=52,			dive=3,	screech=3,	},
["Cave Creeper"]               	= {f=FHH_SPIDER,      	z="Blackrock Depths",         	min=50,	max=52,			bite=7,	},
["Chatter"]                    	= {f=FHH_SPIDER,      	z="Redridge Mountains",       	min=23,			t=2,	bite=3,	},
["Clack the Reaver"]           	= {f=FHH_SCORPID,     	z="Blasted Lands",            	min=53,			t=2,	claw=7,	},
["Clattering Crawler"]         	= {f=FHH_CRAB,        	z="Ashenvale",                	min=19,	max=20,			claw=3,	},
["Cleft Scorpid"]              	= {f=FHH_SCORPID,     	z="Uldaman",                  	min=35,	max=36,			poison=2,	},
["Cloud Serpent"]              	= {f=FHH_WIND_SERPENT,	z="Thousand Needles",         	min=25,	max=26,			lightning=3,	},
["Cobalt Serpent"]             	= {f=FHH_WIND_SERPENT,	z="Sethekk Halls",            	min=68,	max=71,	t=1,	lightning=6,	},
["Coilskar Cobra"]             	= {f=FHH_SERPENT,     	z="Shadowmoon Valley",        	min=68,					spit=3,	},
["Corrupted Mottled Boar"]     	= {f=FHH_BOAR,        	z="Durotar",                  	min=10,	max=11,			charge=1,	},
["Corrupted Scorpid"]          	= {f=FHH_SCORPID,     	z="Durotar",                  	min=10,	max=11,			poison=1,	},
["Coyote"]                     	= {f=FHH_WOLF,        	z="Westfall",                 	min=10,	max=11,			bite=2,	},
["Coyote Packleader"]          	= {f=FHH_WOLF,        	z="Westfall",                 	min=11,	max=12,			bite=2,	howl=1,	},
["Crag Boar"]                  	= {f=FHH_BOAR,        	z="Dun Morogh",               	min=5,	max=6,			charge=1,	},
["Crag Coyote"]                	= {f=FHH_WOLF,        	z="Badlands",                 	min=35,	max=36,			bite=5,	dash=1,	},
["Crag Stalker"]               	= {f=FHH_CAT,         	z="Thousand Needles",         	min=25,	max=26,			cower=3,	},
["Crazed Dragonhawk"]          	= {f=FHH_DRAGONHAWK,  	z="Eversong Woods",           	min=7,	max=8,			firebreath=1,	},
["Creepthess"]                 	= {f=FHH_SPIDER,      	z="Hillsbrad Foothills",      	min=24,			t=2,	bite=3,	},
["Dark Screecher"]             	= {f=FHH_BAT,         	z="Blackrock Depths",         	min=50,	max=52,			cower=5,	dive=3,	screech=3,	},
["Dark Worg"]                  	= {f=FHH_WOLF,        	z="Nagrand",                  	min=64,	max=65,			howl=4,	},
["Darkfang Creeper"]           	= {f=FHH_SPIDER,      	z="Dustwallow Marsh",         	min=37,	max=38,			bite=5,	},
["Deadly Cleft Scorpid"]       	= {f=FHH_SCORPID,     	z="Uldaman",                  	min=37,	max=38,			poison=3,	},
["Deadmire"]                   	= {f=FHH_CROCOLISK,   	z="Dustwallow Marsh",         	min=41,					bite=6,	},
["Death Flayer"]               	= {f=FHH_SCORPID,     	z="Durotar",                  	min=11,			t=2,	claw=2,	poison=1,	},
["Death Howl"]                 	= {f=FHH_WOLF,        	z="Felwood",                  	min=49,			t=2,	bite=6,	howl=3,	},
["Deathlash Scorpid"]          	= {f=FHH_SCORPID,     	z="Burning Steppes",          	min=54,	max=55,			claw=7,	poison=3,	},
["Deathstrike Tarantula"]      	= {f=FHH_SPIDER,      	z="Swamp of Sorrows",         	min=40,	max=41,			bite=6,	},
["Deep Stinger"]               	= {f=FHH_SCORPID,     	z="Blackrock Depths",         	min=50,	max=52,			poison=3,	},
["Deepmoss Creeper"]           	= {f=FHH_SPIDER,      	z="Stonetalon Mountains",     	min=16,	max=17,			bite=3,	},
["Deepmoss Webspinner"]        	= {f=FHH_SPIDER,      	z="Stonetalon Mountains",     	min=19,	max=20,			bite=3,	},
["Den Mother"]                 	= {f=FHH_BEAR,        	z="Darkshore",                	min=18,	max=19,			claw=3,	},
["Deviate Adder"]              	= {f=FHH_SERPENT,     	z="Wailing Caverns",          	min=18,	max=19,	t=1,	spit=1,	},
["Deviate Coiler"]             	= {f=FHH_WIND_SERPENT,	z="Wailing Caverns",          	min=15,	max=16,			lightning=2,	},
["Deviate Coiler Hatchling"]   	= {f=FHH_WIND_SERPENT,	z="Wailing Caverns",          	min=11,					lightning=1,	},
["Deviate Crocolisk"]          	= {f=FHH_CROCOLISK,   	z="Wailing Caverns",          	min=18,	max=19,			bite=3,	},
["Deviate Dreadfang"]          	= {f=FHH_WIND_SERPENT,	z="Wailing Caverns",          	min=19,			t=1,	lightning=2,	},
["Deviate Moccasin"]           	= {f=FHH_SERPENT,     	z="Wailing Caverns",          	min=19,			t=1,	spit=1,	},
["Deviate Stinglash"]          	= {f=FHH_WIND_SERPENT,	z="Wailing Caverns",          	min=16,	max=17,			lightning=2,	},
["Deviate Venomwing"]          	= {f=FHH_WIND_SERPENT,	z="Wailing Caverns",          	min=19,			t=1,	lightning=2,	},
["Deviate Viper"]              	= {f=FHH_SERPENT,     	z="Wailing Caverns",          	min=19,	max=20,	t=1,	spit=1,	},
["Dire Mottled Boar"]          	= {f=FHH_BOAR,        	z="Durotar",                  	min=6,	max=7,			charge=1,},
["Dire Raven"]                 	= {f=FHH_CARRION_BIRD,	z="Blade's Edge Mountains",   	min=67,	max=68,			dive=3,	screech=5,	},
["Diseased Grizzly"]           	= {f=FHH_BEAR,        	z="Western Plaguelands",      	min=55,	max=56,			claw=7,	},
["Diseased Wolf"]              	= {f=FHH_WOLF,        	z="Western Plaguelands",      	min=53,	max=54,			bite=7,	},
["Dread Flyer"]                	= {f=FHH_CARRION_BIRD,	z="Desolace",                 	min=36,	max=37,			dive=1,	},
["Dread Ripper"]               	= {f=FHH_CARRION_BIRD,	z="Desolace",                 	min=39,	max=40,			screech=2,	},
["Dreadfang Lurker"]           	= {f=FHH_SPIDER,      	z="Terokkar Forest",          	min=63,	max=64,			bite=8,	},
["Dreadfang Widow"]            	= {f=FHH_SPIDER,      	z="Terokkar Forest",          	min=64,	max=65,			bite=9,	},
["Dreadmaw Crocolisk"]         	= {f=FHH_CROCOLISK,   	z="Durotar",                  	min=9,	max=11,			bite=1,	},
["Drywallow Crocolisk"]        	= {f=FHH_CROCOLISK,   	z="Dustwallow Marsh",         	min=35,	max=36,			bite=5,	},
["Drywallow Daggermaw"]        	= {f=FHH_CROCOLISK,   	z="Dustwallow Marsh",         	min=39,	max=40,			bite=6,	},
["Drywallow Snapper"]          	= {f=FHH_CROCOLISK,   	z="Dustwallow Marsh",         	min=37,	max=38,			bite=5,	},
["Durotar Tiger"]              	= {f=FHH_CAT,         	z="Durotar",                  	min=7,	max=8,			cower=1,	},
["Eclipsion Dragonhawk"]       	= {f=FHH_DRAGONHAWK,  	z="Shadowmoon Valley",        	min=67,	max=68,			firebreath=2,	},
["Elder Ashenvale Bear"]       	= {f=FHH_BEAR,        	z="Ashenvale",                	min=25,	max=26,			claw=4,	},
["Elder Cloud Serpent"]        	= {f=FHH_WIND_SERPENT,	z="Thousand Needles",         	min=27,	max=29,			lightning=3,	},
["Elder Crag Boar"]            	= {f=FHH_BOAR,        	z="Dun Morogh",               	min=7,	max=8,			charge=1,	},
["Elder Crag Coyote"]          	= {f=FHH_WOLF,        	z="Badlands",                 	min=39,	max=40,			dash=1,	howl=2,	},
["Elder Mistvale Gorilla"]     	= {f=FHH_GORILLA,     	z="Stranglethorn Vale",       	min=40,	max=41,			thunderstomp=2,	},
["Elder Moss Creeper"]         	= {f=FHH_SPIDER,      	z="Hillsbrad Foothills",      	min=26,	max=27,			bite=4,	},
["Elder Mottled Boar"]         	= {f=FHH_BOAR,        	z="Durotar",                  	min=8,	max=9,			charge=1,	},
["Elder Mountain Boar"]        	= {f=FHH_BOAR,        	z="Loch Modan",               	min=16,	max=17,			charge=2,	},
["Elder Plainstrider"]         	= {f=FHH_TALLSTRIDER, 	z="Mulgore",                  	min=8,	max=9,			cower=1,	},
["Elder Shadowmaw Panther"]    	= {f=FHH_CAT,         	z="Stranglethorn Vale",       	min=42,	max=43,			dash=2,	prowl=2,	},
["Elder Shardtooth"]           	= {f=FHH_BEAR,        	z="Winterspring",             	min=57,	max=58,			claw=8,	},
["Elder Springpaw"]            	= {f=FHH_CAT,         	z="Eversong Woods",           	min=8,	max=9,			claw=2,	},
["Encrusted Surf Crawler"]     	= {f=FHH_CRAB,        	z="Durotar",                  	min=9,	max=10,			claw=2,	},
["Enraged Ravager"]            	= {f=FHH_RAVAGER,     	z="Bloodmyst Isle",           	min=16,	max=17,			gore=3,	},
["Felpaw Ravager"]             	= {f=FHH_WOLF,        	z="Felwood",                  	min=51,	max=52,			bite=7,	},
["Felpaw Wolf"]                	= {f=FHH_WOLF,        	z="Felwood",                  	min=47,	max=48,			bite=6,	howl=3,	},
["Felsworn Scalewing"]         	= {f=FHH_WIND_SERPENT,	z="Blade's Edge Mountains",   	min=66,	max=67,			lightning=6,	},
["Female Kaliri Hatchling"]    	= {f=FHH_OWL,         	z="Hellfire Peninsula",       	min=62,					claw=8,	},
["Feral Crag Coyote"]          	= {f=FHH_WOLF,        	z="Badlands",                 	min=37,	max=38,			dash=1,	},
["Feral Dragonhawk Hatchling"] 	= {f=FHH_DRAGONHAWK,  	z="Eversong Woods",           	min=5,	max=6,			firebreath=1,	},
["Feral Mountain Lion"]        	= {f=FHH_CAT,         	z="Hillsbrad Foothills",      	min=27,	max=28,			cower=3,	},
["Ferocious Grizzled Bear"]    	= {f=FHH_BEAR,        	z="Silverpine Forest",        	min=11,	max=12,			claw=2,	},
["Fire Roc"]                   	= {f=FHH_CARRION_BIRD,	z="Tanaris",                  	min=43,	max=45,			dive=2,	},
["Firetail Scorpid"]           	= {f=FHH_SCORPID,     	z="Burning Steppes",          	min=56,	max=57,			poison=4,	},
["Flatland Cougar"]            	= {f=FHH_CAT,         	z="Mulgore",                  	min=7,	max=8,			cower=1,	},
["Fleeting Plainstrider"]      	= {f=FHH_TALLSTRIDER, 	z="The Barrens",              	min=12,	max=13,			cower=1,	},
["Forest Lurker"]              	= {f=FHH_SPIDER,      	z="Loch Modan",               	min=10,	max=11,			bite=2,	},
["Forest Moss Creeper"]        	= {f=FHH_SPIDER,      	z="Hillsbrad Foothills",      	min=20,	max=21,			bite=3,	},
["Forest Spider"]              	= {f=FHH_SPIDER,      	z="Elwynn Forest",            	min=5,	max=6,			bite=1,	},
["Foreststrider Fledgling"]    	= {f=FHH_TALLSTRIDER, 	z="Darkshore",                	min=11,	max=13,			cower=1,	},
["Frostsaber Cub"]             	= {f=FHH_CAT,         	z="Winterspring",             	min=55,	max=56,			cower=6,	},
["Frostsaber Huntress"]        	= {f=FHH_CAT,         	z="Winterspring",             	min=58,	max=59,			dash=3,	},
["Frostsaber Stalker"]         	= {f=FHH_CAT,         	z="Winterspring",             	min=59,	max=60,			prowl=3,	dash=3,	},
["Ghamoo-ra"]                  	= {f=FHH_TURTLE,      	z="Blackfathom Deeps",        	min=23,			t=1,	bite=4,	shell=1,	},
["Ghost Saber"]                	= {f=FHH_CAT,         	z="Darkshore",                	min=19,	max=20,			claw=3,	},
["Ghostclaw Lynx"]             	= {f=FHH_CAT,         	z="Ghostlands",               	min=13,	max=14,			claw=2,	},
["Ghostclaw Ravager"]          	= {f=FHH_CAT,         	z="Ghostlands",               	min=16,	max=17,			bite=3,	claw=3,	},
["Ghostpaw Alpha"]             	= {f=FHH_WOLF,        	z="Ashenvale",                	min=27,	max=28,			bite=4,	howl=2,	},
["Ghostpaw Runner"]            	= {f=FHH_WOLF,        	z="Ashenvale",                	min=19,	max=20,			bite=3,	},
["Giant Foreststrider"]        	= {f=FHH_TALLSTRIDER, 	z="Darkshore",                	min=17,	max=19,			cower=2,	},
["Giant Moss Creeper"]         	= {f=FHH_SPIDER,      	z="Hillsbrad Foothills",      	min=24,	max=25,			bite=4,	},
["Giant Plains Creeper"]       	= {f=FHH_SPIDER,      	z="Arathi Highlands",         	min=35,	max=36,			bite=5,	},
["Giant Webwood Spider"]       	= {f=FHH_SPIDER,      	z="Teldrassil",               	min=10,	max=11,			bite=2,	},
["Giant Wetlands Crocolisk"]   	= {f=FHH_CROCOLISK,   	z="Wetlands",                 	min=25,	max=26,			bite=4,	},
["Githyiss the Vile"]          	= {f=FHH_SPIDER,      	z="Teldrassil",               	min=5,					bite=1,	},
["Goretusk"]                   	= {f=FHH_BOAR,        	z="Westfall",                 	min=14,	max=15,			charge=2,	},
["Gray Bear"]                  	= {f=FHH_BEAR,        	z="Hillsbrad Foothills",      	min=21,	max=22,			claw=3,	},
["Gray Forest Wolf"]           	= {f=FHH_WOLF,        	z="Elwynn Forest",            	min=7,	max=8,			bite=1,	},
["Great Goretusk"]             	= {f=FHH_BOAR,        	z="Westfall",                 	min=16,	max=17,			charge=2,	},
["Greater Duskbat"]            	= {f=FHH_BAT,         	z="Tirisfal Glades",          	min=6,	max=7,			cower=1,	},
["Greater Firebird"]           	= {f=FHH_CARRION_BIRD,	z="Tanaris",                  	min=46,			t=2,	dive=2,	},
["Greater Fleshripper"]        	= {f=FHH_CARRION_BIRD,	z="Westfall",                 	min=16,	max=17,			screech=1,	},
["Greater Kraul Bat"]          	= {f=FHH_BAT,         	z="Razorfen Kraul",           	min=26,			t=1,	dive=1,	},
["Greater Tarantula"]          	= {f=FHH_SPIDER,      	z="Redridge Mountains",       	min=19,	max=20,			bite=3,	},
["Greater Thunderhawk"]        	= {f=FHH_WIND_SERPENT,	z="The Barrens",              	min=23,	max=24,			lightning=2,	},
["Greater Windroc"]            	= {f=FHH_OWL,         	z="Nagrand",                  	min=66,	max=67,			claw=9,	screech=5,	},
["Green Recluse"]              	= {f=FHH_SPIDER,      	z="Duskwood",                 	min=21,	max=22,			bite=3,	},
["Groddoc Thunderer"]          	= {f=FHH_GORILLA,     	z="Feralas",                  	min=49,	max=50,			thunderstomp=2,	},
["Grovestalker Lynx"]          	= {f=FHH_CAT,         	z="Blade's Edge Mountains",   	min=65,	max=66,			cower=7,	},
["Grunter"]                    	= {f=FHH_BOAR,        	z="Blasted Lands",            	min=50,			t=2,	charge=5,	dash=3,	},
["Gutripper"]                  	= {f=FHH_OWL,         	z="Nagrand",                  	min=67,			t=1,	claw=9,	screech=5,	},
["Hakkari Frostwing"]          	= {f=FHH_WIND_SERPENT,	z="The Temple of Atal'Hakkar",	min=48,	max=49,	t=1,	lightning=5,	},
["Hakkari Sapper"]             	= {f=FHH_WIND_SERPENT,	z="The Temple of Atal'Hakkar",	min=48,	max=49,	t=1,	lightning=5,	},
["Ice Claw Bear"]              	= {f=FHH_BEAR,        	z="Dun Morogh",               	min=7,	max=8,			claw=1,	},
["Ironback"]                   	= {f=FHH_TURTLE,      	z="The Hinterlands",          	min=51,			t=2,	bite=7,	shell=1,	},
["Ironbeak Hunter"]            	= {f=FHH_OWL,         	z="Felwood",                  	min=50,	max=51,			claw=7,	dive=3,	},
["Ironbeak Owl"]               	= {f=FHH_OWL,         	z="Felwood",                  	min=48,	max=49,			dive=2,	screech=3,	},
["Ironbeak Screecher"]         	= {f=FHH_OWL,         	z="Felwood",                  	min=52,	max=53,			dive=3,	},
["Ironfur Bear"]               	= {f=FHH_BEAR,        	z="Feralas",                  	min=41,	max=42,			claw=6,	},
["Ironfur Patriarch"]          	= {f=FHH_BEAR,        	z="Feralas",                  	min=48,	max=49,			claw=7,	},
["Jaguero Stalker"]            	= {f=FHH_CAT,         	z="Stranglethorn Vale",       	min=41,					cower=5,	prowl=3,	},
["Jungle Thunderer"]           	= {f=FHH_GORILLA,     	z="Stranglethorn Vale",       	min=37,	max=38,			thunderstomp=1,	},
["Juvenile Snow Leopard"]      	= {f=FHH_CAT,         	z="Dun Morogh",               	min=5,	max=6,			cower=1,	},
["Kaliri Matriarch"]           	= {f=FHH_OWL,         	z="Hellfire Peninsula",       	min=63,					screech=4,	},
["Kaliri Swooper"]             	= {f=FHH_OWL,         	z="Hellfire Peninsula",       	min=60,					dive=3,	},
["King Bangalash"]             	= {f=FHH_CAT,         	z="Stranglethorn Vale",       	min=43,			t=1,	dash=2,	claw=6,	},
["Kraul Bat"]                  	= {f=FHH_BAT,         	z="Razorfen Kraul",           	min=26,			t=1,	cower=3,	dive=1,	},
["Krellack"]                   	= {f=FHH_SCORPID,     	z="Silithus",                 	min=56,			t=2,	poison=4,	},
["Kresh"]                      	= {f=FHH_TURTLE,      	z="Wailing Caverns",          	min=20,			t=1,	bite=3,	shell=1,	},
["Kurzen War Tiger"]           	= {f=FHH_CAT,         	z="Stranglethorn Vale",       	min=32,	max=33,			dash=1,	},
["Lady Sathrah"]               	= {f=FHH_SPIDER,      	z="Teldrassil",               	min=12,					bite=2,	},
["Large Crag Boar"]            	= {f=FHH_BOAR,        	z="Dun Morogh",               	min=6,	max=7,			charge=1,	},
["Large Loch Crocolisk"]       	= {f=FHH_CROCOLISK,   	z="Loch Modan",               	min=22,			t=2,	bite=3,	},
["Leech Widow"]                	= {f=FHH_SPIDER,      	z="Wetlands",                 	min=24,			t=2,	bite=4,	},
["Loch Crocolisk"]             	= {f=FHH_CROCOLISK,   	z="Loch Modan",               	min=14,	max=15,			bite=2,	},
["Longsnout"]                  	= {f=FHH_BOAR,        	z="Elwynn Forest",            	min=10,	max=11,			charge=1,	},
["Longtooth Howler"]           	= {f=FHH_WOLF,        	z="Feralas",                  	min=43,	max=44,			howl=3,	},
["Longtooth Runner"]           	= {f=FHH_WOLF,        	z="Feralas",                  	min=40,	max=41,			bite=6,	dash=2,	howl=3,	},
["Lost Torranche"]             	= {f=FHH_TALLSTRIDER, 	z="Terokkar Forest",          	min=70,					cower=7,	},
["Lupos"]                      	= {f=FHH_WOLF,        	z="Duskwood",                 	min=23,			t=2,	bite=3,	},
["Magram Bonepaw"]             	= {f=FHH_HYENA,       	z="Desolace",                 	min=37,	max=38,			dash=1,	},
["Male Kaliri Hatchling"]      	= {f=FHH_OWL,         	z="Hellfire Peninsula",       	min=61,					claw=8,	},
["Mangeclaw"]                  	= {f=FHH_BEAR,        	z="Dun Morogh",               	min=11,					claw=2,	},
["Mangy Mountain Boar"]        	= {f=FHH_BOAR,        	z="Loch Modan",               	min=14,	max=15,			charge=2,	},
["Mazzranache"]                	= {f=FHH_TALLSTRIDER, 	z="Mulgore",                  	min=9,			t=2,	cower=1,	},
["Mesa Buzzard"]               	= {f=FHH_CARRION_BIRD,	z="Arathi Highlands",         	min=34,	max=35,			dive=1,	},
["Mist Howler"]                	= {f=FHH_WOLF,        	z="Ashenvale",                	min=22,			t=2,	howl=1,	},
["Mistvale Gorilla"]           	= {f=FHH_GORILLA,     	z="Stranglethorn Vale",       	min=32,	max=33,			thunderstomp=1,	},
["Mongress"]                   	= {f=FHH_BEAR,        	z="Felwood",                  	min=50,			t=2,	claw=7,	},
["Monstrous Crawler"]          	= {f=FHH_CRAB,        	z="Swamp of Sorrows",         	min=43,	max=44,			claw=6,	},
["Monstrous Plaguebat"]        	= {f=FHH_BAT,         	z="Eastern Plaguelands",      	min=56,	max=58,			cower=6,	screech=4,	},
["Moonstalker Runt"]           	= {f=FHH_CAT,         	z="Darkshore",                	min=10,	max=11,			cower=1,	},
["Moonstalker Sire"]           	= {f=FHH_CAT,         	z="Darkshore",                	min=17,	max=18,			cower=2,	},
["Mottled Boar"]               	= {f=FHH_BOAR,        	z="Durotar",                  	min=1,	max=2,			charge=1,	},
["Mottled Drywallow Crocolisk"]	= {f=FHH_CROCOLISK,   	z="Dustwallow Marsh",         	min=38,	max=39,			bite=5,	},
["Mountain Boar"]              	= {f=FHH_BOAR,        	z="Loch Modan",               	min=10,	max=11,			charge=1,	},
["Mountain Lion"]              	= {f=FHH_CAT,         	z="Alterac Mountains",        	min=32,	max=33,			prowl=1,	},
["Murderous Blisterpaw"]       	= {f=FHH_HYENA,       	z="Tanaris",                  	min=43,			t=2,	dash=2,	},
["Murk Slitherer"]             	= {f=FHH_SERPENT,     	z="The Temple of Atal'Hakkar",	min=45,	max=46,			spit=2,	},
["Murk Spitter"]               	= {f=FHH_SERPENT,     	z="The Temple of Atal'Hakkar",	min=46,	max=47,			spit=2,	},
["Naraxis"]                    	= {f=FHH_SPIDER,      	z="Duskwood",                 	min=27,			t=2,	bite=4,	},
["Night Web Matriarch"]        	= {f=FHH_SPIDER,      	z="Tirisfal Glades",          	min=5,					bite=1,	},
["Night Web Spider"]           	= {f=FHH_SPIDER,      	z="Tirisfal Glades",          	min=3,	max=4,			bite=1,	},
["Nightsaber"]                 	= {f=FHH_CAT,         	z="Teldrassil",               	min=5,	max=6,			cower=1,	},
["Noxious Flayer"]             	= {f=FHH_WIND_SERPENT,	z="Dustwallow Marsh",         	min=35,	max=36,			dive=1,	},
["Noxious Plaguebat"]          	= {f=FHH_BAT,         	z="Eastern Plaguelands",      	min=54,	max=56,			cower=5,	},
["Noxious Reaver"]             	= {f=FHH_WIND_SERPENT,	z="Dustwallow Marsh",         	min=37,	max=38,			dive=1,	lightning=4,	},
["Noxious Shredder"]           	= {f=FHH_WIND_SERPENT,	z="Dustwallow Marsh",         	min=38,	max=39,			dive=1,	lightning=4,	},
["Oasis Snapjaw"]              	= {f=FHH_TURTLE,      	z="The Barrens",              	min=15,	max=16,			bite=2,	},
["Ol' Sooty"]                  	= {f=FHH_BEAR,        	z="Loch Modan",               	min=20,					claw=3,	},
["Old Cliff Jumper"]           	= {f=FHH_WOLF,        	z="The Hinterlands",          	min=42,			t=2,	bite=6,	dash=2,	},
["Old Grizzlegut"]             	= {f=FHH_BEAR,        	z="Feralas",                  	min=43,			t=2,	claw=6,	},
["Olm the Wise"]               	= {f=FHH_OWL,         	z="Felwood",                  	min=52,			t=2,	claw=7,	dive=3,	},
["Ornery Plainstrider"]        	= {f=FHH_TALLSTRIDER, 	z="The Barrens",              	min=16,	max=17,			cower=2,	},
["Panther"]                    	= {f=FHH_CAT,         	z="Stranglethorn Vale",       	min=32,	max=33,			cower=3,	},
["Phoenix-Hawk Hatchling"]     	= {f=FHH_DRAGONHAWK,  	z="Tempest Keep",             	min=70,			t=1,	firebreath=2,	},
["Plague Lurker"]              	= {f=FHH_SPIDER,      	z="Western Plaguelands",      	min=54,	max=55,			bite=7,	},
["Plaguebat"]                  	= {f=FHH_BAT,         	z="Eastern Plaguelands",      	min=53,	max=55,			cower=5,	dive=3,	},
["Plagued Swine"]              	= {f=FHH_BOAR,        	z="Eastern Plaguelands",      	min=60,					charge=6,	},
["Plains Creeper"]             	= {f=FHH_SPIDER,      	z="Arathi Highlands",         	min=32,	max=33,			bite=5,	},
["Porcine Entourage"]          	= {f=FHH_BOAR,        	z="Elwynn Forest",            	min=7,					charge=1,	},
["Prairie Stalker"]            	= {f=FHH_WOLF,        	z="Mulgore",                  	min=7,	max=8,			bite=1,	},
["Prairie Wolf"]               	= {f=FHH_WOLF,        	z="Mulgore",                  	min=5,	max=6,			bite=1,	},
["Prairie Wolf Alpha"]         	= {f=FHH_WOLF,        	z="Mulgore",                  	min=9,	max=10,			bite=2,	},
["Princess"]                   	= {f=FHH_BOAR,        	z="Elwynn Forest",            	min=9,					charge=1,	},
["Prowler"]                    	= {f=FHH_WOLF,        	z="Elwynn Forest",            	min=9,	max=10,			bite=2,	},
["Pygmy Surf Crawler"]         	= {f=FHH_CRAB,        	z="Durotar",                  	min=5,	max=6,			claw=1,	},
["Quillfang Ravager"]          	= {f=FHH_RAVAGER,     	z="Hellfire Peninsula",       	min=62,	max=63,			bite=8,	},
["Quillfang Skitterer"]        	= {f=FHH_RAVAGER,     	z="Hellfire Peninsula",       	min=61,	max=62,			gore=8,	},
["Rabid Blisterpaw"]           	= {f=FHH_HYENA,       	z="Tanaris",                  	min=47,	max=48,			dash=2,	},
["Rabid Crag Coyote"]          	= {f=FHH_WOLF,        	z="Badlands",                 	min=42,	max=43,			dash=2,	},
["Ragged Scavenger"]           	= {f=FHH_WOLF,        	z="Tirisfal Glades",          	min=2,	max=3,			bite=1,	},
["Raging Agam'ar"]             	= {f=FHH_BOAR,        	z="Razorfen Kraul",           	min=25,			t=1,	charge=3,	},
["Rak'Shiri"]                  	= {f=FHH_CAT,         	z="Winterspring",             	min=57,			t=2,	dash=3,	},
["Ravage"]                     	= {f=FHH_HYENA,       	z="Blasted Lands",            	min=51,			t=2,	dash=3,	},
["Ravager Specimen"]           	= {f=FHH_RAVAGER,     	z="Azuremyst Isle",           	min=9,	max=10,			bite=2,	},
["Ravenous Windroc"]           	= {f=FHH_OWL,         	z="Nagrand",                  	min=65,	max=66,			claw=9,	},
["Razorfang Hatchling"]        	= {f=FHH_RAVAGER,     	z="Hellfire Peninsula",       	min=59,	max=60,			dash=3,	},
["Razzashi Adder"]             	= {f=FHH_SERPENT,     	z="Zul'Gurub",                	min=60,			t=1,	spit=3,	},
["Razzashi Broodwidow"]        	= {f=FHH_SPIDER,      	z="Zul'Gurub",                	min=61,			t=1,	bite=8,	},
["Razzashi Cobra"]             	= {f=FHH_SERPENT,     	z="Zul'Gurub",                	min=60,			t=1,	spit=3,	},
["Razzashi Serpent"]           	= {f=FHH_SERPENT,     	z="Zul'Gurub",                	min=60,			t=1,	spit=3,	},
["Rekk'tilac"]                 	= {f=FHH_SPIDER,      	z="Searing Gorge",            	min=48,			t=2,	bite=7,	},
["Rema"]                       	= {f=FHH_WOLF,        	z="Blade's Edge Mountains",   	min=66,					bite=9,	howl=4,	},
["Ridge Huntress"]             	= {f=FHH_CAT,         	z="Badlands",                 	min=38,	max=39,			cower=4,	},
["Ridge Stalker"]              	= {f=FHH_CAT,         	z="Badlands",                 	min=36,	max=37,			cower=4,	prowl=1,	},
["Ridge Stalker Patriarch"]    	= {f=FHH_CAT,         	z="Badlands",                 	min=40,	max=41,			dash=2,	prowl=2,	},
["Rip-Blade Ravager"]          	= {f=FHH_RAVAGER,     	z="Blade's Edge Mountains",   	min=63,					dash=3,	},
["Ripfang Lynx"]               	= {f=FHH_CAT,         	z="Netherstorm",              	min=68,	max=69,			claw=9,	cower=7,	},
["Ripscale"]                   	= {f=FHH_CROCOLISK,   	z="Dustwallow Marsh",         	min=37,			t=2,	bite=6,	},
["Roc"]                        	= {f=FHH_CARRION_BIRD,	z="Tanaris",                  	min=42,	max=43,			dive=2,	},
["Rockhide Boar"]              	= {f=FHH_BOAR,        	z="Elwynn Forest",            	min=7,	max=8,			charge=1,	},
["Rogue Vale Screecher"]       	= {f=FHH_WIND_SERPENT,	z="Feralas",                  	min=44,	max=46,			dive=2,	lightning=4,	},
["Rotting Agam'ar"]            	= {f=FHH_BOAR,        	z="Razorfen Kraul",           	min=26,			t=1,	charge=3,	},
["Salt Flats Vulture"]         	= {f=FHH_CARRION_BIRD,	z="Thousand Needles",         	min=32,	max=34,			screech=2,	},
["Saltwater Snapjaw"]          	= {f=FHH_TURTLE,      	z="The Hinterlands",          	min=49,	max=50,			bite=7,	},
["Sandfury Guardian"]          	= {f=FHH_SERPENT,     	z="Zul'Farrak",               	min=45,	max=46,	t=1,	spit=2,	},
["Sarkoth"]                    	= {f=FHH_SCORPID,     	z="Durotar",                  	min=4,					claw=1,	},
["Savannah Patriarch"]         	= {f=FHH_CAT,         	z="The Barrens",              	min=15,	max=16,			cower=2,	},
["Sawtooth Snapper"]           	= {f=FHH_CROCOLISK,   	z="Swamp of Sorrows",         	min=41,	max=42,			bite=6,	},
["Scalewing Serpent"]          	= {f=FHH_WIND_SERPENT,	z="Blade's Edge Mountains",   	min=66,	max=67,			lightning=6,	},
["Scarlet Tracking Hound"]     	= {f=FHH_HYENA,       	z="Scarlet Monastery",        	min=33,	max=34,	t=1,	dash=1,	},
["Scarred Crag Boar"]          	= {f=FHH_BOAR,        	z="Dun Morogh",               	min=9,	max=10,			charge=1,	},
["Scarshield Worg"]            	= {f=FHH_WOLF,        	z="Blackrock Spire",          	min=53,	max=54,			dash=3,	},
["Scorchshell Pincer"]         	= {f=FHH_SCORPID,     	z="Shadowmoon Valley",        	min=68,	max=69,			poison=5,	},
["Scorpashi Lasher"]           	= {f=FHH_SCORPID,     	z="Desolace",                 	min=34,	max=35,			claw=5,	poison=2,	},
["Scorpashi Snapper"]          	= {f=FHH_SCORPID,     	z="Desolace",                 	min=30,	max=31,			claw=4,	poison=2,	},
["Scorpashi Venomlash"]        	= {f=FHH_SCORPID,     	z="Desolace",                 	min=38,	max=39,			poison=2,	},
["Scorpid Bonecrawler"]        	= {f=FHH_SCORPID,     	z="Terokkar Forest",          	min=64,	max=65,			claw=9,	poison=5,	},
["Scorpid Duneburrower"]       	= {f=FHH_SCORPID,     	z="Tanaris",                  	min=46,	max=47,			poison=3,	},
["Scorpid Dunestalker"]        	= {f=FHH_SCORPID,     	z="Tanaris",                  	min=46,	max=47,			poison=3,	},
["Scorpid Hunter"]             	= {f=FHH_SCORPID,     	z="Tanaris",                  	min=40,	max=41,			claw=6,	poison=3,	},
["Scorpid Reaver"]             	= {f=FHH_SCORPID,     	z="Thousand Needles",         	min=31,	max=32,			claw=4,	poison=2,	},
["Scorpid Tail Lasher"]        	= {f=FHH_SCORPID,     	z="Tanaris",                  	min=43,	max=44,			poison=3,	},
["Scorpid Terror"]             	= {f=FHH_SCORPID,     	z="Thousand Needles",         	min=33,	max=34,			poison=2,	},
["Scorpid Worker"]             	= {f=FHH_SCORPID,     	z="Durotar",                  	min=3,					claw=1,	},
["Scorpok Stinger"]            	= {f=FHH_SCORPID,     	z="Blasted Lands",            	min=46,	max=47,			poison=3,	},
["Scythetooth Raptor"]         	= {f=FHH_RAPTOR,      	z="Netherstorm",              	min=68,	max=69,			bite=9,	dash=3,	},
["Searing Roc"]                	= {f=FHH_CARRION_BIRD,	z="Tanaris",                  	min=47,	max=49,			dive=2,	},
["Sewer Beast"]                	= {f=FHH_CROCOLISK,   	z="Stormwind City",           	min=50,			t=2,	bite=7,	},
["Shadow Panther"]             	= {f=FHH_CAT,         	z="Swamp of Sorrows",         	min=39,	max=40,			prowl=1,	},
["Shadowmaw Panther"]          	= {f=FHH_CAT,         	z="Stranglethorn Vale",       	min=37,	max=38,			prowl=1,	},
["Shadowwing Owl"]             	= {f=FHH_OWL,         	z="Shadowmoon Valley",        	min=66,	max=67,			claw=9,	dive=3,	},
["Shanda the Spinner"]         	= {f=FHH_SPIDER,      	z="Loch Modan",               	min=19,			t=2,	bite=3,	},
["Shardtooth Bear"]            	= {f=FHH_BEAR,        	z="Winterspring",             	min=53,	max=54,			claw=7,	},
["Shore Crawler"]              	= {f=FHH_CRAB,        	z="Westfall",                 	min=17,	max=18,			claw=3,	},
["Shrike Bat"]                 	= {f=FHH_BAT,         	z="Uldaman",                  	min=37,	max=38,	t=1,	cower=4,	dive=1,	screech=2,	},
["Silithid Creeper"]           	= {f=FHH_SCORPID,     	z="The Barrens",              	min=20,	max=21,			poison=1,	},
["Silithid Swarmer"]           	= {f=FHH_SCORPID,     	z="The Barrens",              	min=21,	max=22,			poison=1,	},
["Silt Crawler"]               	= {f=FHH_CRAB,        	z="Swamp of Sorrows",         	min=40,	max=41,			claw=6,	},
["Silvermane Howler"]          	= {f=FHH_WOLF,        	z="The Hinterlands",          	min=45,	max=46,			howl=2,	},
["Silvermane Stalker"]         	= {f=FHH_WOLF,        	z="The Hinterlands",          	min=47,	max=48,			dash=2,	},
["Silvermane Wolf"]            	= {f=FHH_WOLF,        	z="The Hinterlands",          	min=43,	max=44,			howl=3,	},
["Sin'Dall"]                   	= {f=FHH_CAT,         	z="Stranglethorn Vale",       	min=37,					dash=1,	},
["Skettis Kaliri"]             	= {f=FHH_OWL,         	z="Terokkar Forest",          	min=70,					dive=3,	},
["Skittering Crustacean"]      	= {f=FHH_CRAB,        	z="Blackfathom Deeps",        	min=22,	max=23,	t=1,	claw=3,	},
["Small Crag Boar"]            	= {f=FHH_BOAR,        	z="Dun Morogh",               	min=3,					charge=1,	},
["Snapjaw"]                    	= {f=FHH_TURTLE,      	z="Hillsbrad Foothills",      	min=30,	max=31,			bite=4,	shell=1,	},
["Snapping Crustacean"]        	= {f=FHH_CRAB,        	z="Blackfathom Deeps",        	min=22,	max=23,	t=1,	claw=3,	},
["Snarler"]                    	= {f=FHH_WOLF,        	z="Feralas",                  	min=42,			t=2,	bite=6,	howl=3,	},
["Snow Tracker Wolf"]          	= {f=FHH_WOLF,        	z="Dun Morogh",               	min=6,	max=7,			bite=1,	},
["Son of Hakkar"]              	= {f=FHH_WIND_SERPENT,	z="Zul'Gurub",                	min=60,			t=1,	lightning=6,	},
["Soulflayer"]                 	= {f=FHH_WIND_SERPENT,	z="Zul'Gurub",                	min=61,			t=1,	lightning=6,	},
["Sparkleshell Snapper"]       	= {f=FHH_TURTLE,      	z="Thousand Needles",         	min=34,	max=35,			bite=5,	},
["Spawn of Hakkar"]            	= {f=FHH_WIND_SERPENT,	z="The Temple of Atal'Hakkar",	min=49,			t=1,	dive=3,	lightning=5,	},
["Spiteflayer"]                	= {f=FHH_CARRION_BIRD,	z="Blasted Lands",            	min=52,			t=2,	dive=3,	},
["Spot"]                       	= {f=FHH_WOLF,        	z="Dustwallow Marsh",         	min=35,					dash=1,	},
["Starving Blisterpaw"]        	= {f=FHH_HYENA,       	z="Tanaris",                  	min=41,	max=42,			dash=2,	},
["Starving Mountain Lion"]     	= {f=FHH_CAT,         	z="Hillsbrad Foothills",      	min=23,	max=24,			cower=2,	},
["Starving Winter Wolf"]       	= {f=FHH_WOLF,        	z="Dun Morogh",               	min=8,	max=9,			bite=2,	},
["Stolid Snapjaw"]             	= {f=FHH_TURTLE,      	z="Maraudon",                 	min=46,	max=47,			bite=6,	},
["Stonelash Flayer"]           	= {f=FHH_SCORPID,     	z="Silithus",                 	min=57,	max=58,			poison=4,	},
["Stonelash Pincer"]           	= {f=FHH_SCORPID,     	z="Silithus",                 	min=56,	max=57,			poison=4,	},
["Stonelash Scorpid"]          	= {f=FHH_SCORPID,     	z="Silithus",                 	min=54,	max=55,			poison=3,	},
["Stonetusk Boar"]             	= {f=FHH_BOAR,        	z="Elwynn Forest",            	min=7,	max=8,			charge=1,	},
["Stranglethorn Tiger"]        	= {f=FHH_CAT,         	z="Stranglethorn Vale",       	min=32,	max=33,			dash=1,	},
["Strigid Hunter"]             	= {f=FHH_OWL,         	z="Teldrassil",               	min=8,	max=9,			claw=2,	},
["Strigid Owl"]                	= {f=FHH_OWL,         	z="Teldrassil",               	min=5,	max=6,			claw=1,	},
["Swamp Jaguar"]               	= {f=FHH_CAT,         	z="Swamp of Sorrows",         	min=36,	max=37,			dash=1,	},
["Swiftwing Shredder"]         	= {f=FHH_WIND_SERPENT,	z="Netherstorm",              	min=68,	max=69,			lightning=6,	},
["Tarantula"]                  	= {f=FHH_SPIDER,      	z="Redridge Mountains",       	min=15,	max=16,			bite=2,	},
["Thistle Bear"]               	= {f=FHH_BEAR,        	z="Darkshore",                	min=11,	max=12,			claw=2,	},
["Thistle Boar"]               	= {f=FHH_BOAR,        	z="Teldrassil",               	min=2,	max=3,			charge=1,   },
["Thornfang Venomspitter"]     	= {f=FHH_RAVAGER,     	z="Hellfire Peninsula",       	min=62,	max=63,			bite=8,	},
["Thunderhawk Cloudscraper"]   	= {f=FHH_WIND_SERPENT,	z="The Barrens",              	min=20,	max=22,			lightning=2,	},
["Thunderhawk Hatchling"]      	= {f=FHH_WIND_SERPENT,	z="The Barrens",              	min=18,	max=20,			lightning=2,	},
["Tide Crawler"]               	= {f=FHH_CRAB,        	z="Darkshore",                	min=12,	max=14,			claw=2,	},
["Timber"]                     	= {f=FHH_WOLF,        	z="Dun Morogh",               	min=10,			t=2,	bite=2,	},
["Timber Worg"]                	= {f=FHH_WOLF,        	z="Terokkar Forest",          	min=62,	max=63,			howl=4,	},
["Timberweb Recluse"]          	= {f=FHH_SPIDER,      	z="Azshara",                  	min=47,	max=48,			bite=6,	},
["Twilight Runner"]            	= {f=FHH_CAT,         	z="Stonetalon Mountains",     	min=23,	max=24,			cower=2,	},
["U'cha"]                      	= {f=FHH_GORILLA,     	z="Un'Goro Crater",           	min=55,					thunderstomp=3,	},
["Uhk'loc"]                    	= {f=FHH_GORILLA,     	z="Un'Goro Crater",           	min=52,	max=53,	t=2,	bite=7,	},
["Un'Goro Thunderer"]          	= {f=FHH_GORILLA,     	z="Un'Goro Crater",           	min=52,	max=53,			thunderstomp=3,	},
["Vale Screecher"]             	= {f=FHH_WIND_SERPENT,	z="Feralas",                  	min=41,	max=43,			dive=2,	lightning=4,	},
["Venomlash Scorpid"]          	= {f=FHH_SCORPID,     	z="Uldaman",                  	min=37,	max=38,	t=1,	claw=5,	},
["Venomous Cloud Serpent"]     	= {f=FHH_WIND_SERPENT,	z="Thousand Needles",         	min=26,	max=28,			lightning=3,	},
["Venomtail Scorpid"]          	= {f=FHH_SCORPID,     	z="Durotar",                  	min=9,	max=10,			claw=2,	poison=1,	},
["Venomtip Scorpid"]           	= {f=FHH_SCORPID,     	z="Burning Steppes",          	min=52,	max=53,			poison=3,	},
["Vicious Night Web Spider"]   	= {f=FHH_SPIDER,      	z="Tirisfal Glades",          	min=9,	max=10,			bite=2,	},
["Vile Sting"]                 	= {f=FHH_SCORPID,     	z="Thousand Needles",         	min=35,			t=2,	claw=5,	poison=2,	},
["Vilebranch Raiding Wolf"]    	= {f=FHH_WOLF,        	z="The Hinterlands",          	min=50,	max=51,			bite=7,	dash=3,	},
["Warp Chaser"]                	= {f=FHH_WARP_STALKER,	z="Netherstorm",              	min=67,	max=68,			warp=1,	},
["Warp Hunter"]                	= {f=FHH_WARP_STALKER,	z="Terokkar Forest",          	min=64,	max=65,			warp=1,	},
["Warp Stalker"]               	= {f=FHH_WARP_STALKER,	z="Terokkar Forest",          	min=63,	max=64,			warp=1,	},
["Washte Pawne"]               	= {f=FHH_WIND_SERPENT,	z="The Barrens",              	min=25,					lightning=3,	},
["Wayward Buzzard"]            	= {f=FHH_CARRION_BIRD,	z="Badlands",                 	min=35,	max=37,			dive=1,	},
["Webwood Silkspinner"]        	= {f=FHH_SPIDER,      	z="Teldrassil",               	min=8,	max=9,			bite=2,	},
["Webwood Venomfang"]          	= {f=FHH_SPIDER,      	z="Teldrassil",               	min=7,	max=8,			bite=1,	},
["Wildthorn Lurker"]           	= {f=FHH_SPIDER,      	z="Ashenvale",                	min=28,	max=29,			bite=4,	},
["Windroc"]                    	= {f=FHH_OWL,         	z="Nagrand",                  	min=64,	max=65,			dive=3,	},
["Windroc Matriarch"]          	= {f=FHH_OWL,         	z="Nagrand",                  	min=66,			t=1,	dive=3,	screech=5,	},
["Winter Wolf"]                	= {f=FHH_WOLF,        	z="Dun Morogh",               	min=7,	max=8,			bite=1,	},
["Winterspring Owl"]           	= {f=FHH_OWL,         	z="Winterspring",             	min=54,	max=56,			claw=7,	dive=3,	},
["Winterspring Screecher"]     	= {f=FHH_OWL,         	z="Winterspring",             	min=57,	max=59,			claw=8,	dive=3,	screech=4,	},
["Wood Lurker"]                	= {f=FHH_SPIDER,      	z="Loch Modan",               	min=17,	max=18,			bite=3,	},
["Worg"]                       	= {f=FHH_WOLF,        	z="Silverpine Forest",        	min=10,	max=11,			bite=2,	howl=1,	},
["Young Forest Bear"]          	= {f=FHH_BEAR,        	z="Elwynn Forest",            	min=8,	max=9,			claw=2,	},
["Young Goretusk"]             	= {f=FHH_BOAR,        	z="Westfall",                 	min=12,	max=13,			charge=2,	},
["Young Mesa Buzzard"]         	= {f=FHH_CARRION_BIRD,	z="Arathi Highlands",         	min=31,	max=32,			dive=1,	},
["Young Panther"]              	= {f=FHH_CAT,         	z="Stranglethorn Vale",       	min=30,	max=31,			cower=3,	},
["Young Stranglethorn Tiger"]  	= {f=FHH_CAT,         	z="Stranglethorn Vale",       	min=30,	max=31,			cower=3,	},
["Young Thistle Boar"]         	= {f=FHH_BOAR,        	z="Teldrassil",               	min=1,	max=2,			charge=1,	},
["Zaricotl"]                   	= {f=FHH_CARRION_BIRD,	z="Badlands",                 	min=55,			t=3,	dive=3,	},
["Zulian Panther"]             	= {f=FHH_CAT,         	z="Zul'Gurub",                	min=60,			t=1,	dash=3,	},
["Zulian Stalker"]             	= {f=FHH_CAT,         	z="Zul'Gurub",                	min=61,			t=1,	dash=3,	prowl=3,	},
}

