language: minimal

jobs:
  include:
    - name: 'Classic'
      install:
        - export GAME_VERSION="classic"
        - git clone https://github.com/Gethe/wow-ui-source tests/wow-ui-source -b classic
        - wget -q -O LibHunterPetInfo.zip https://github.com/Beast-Masters-addons/LibHunterPetInfo/releases/download/v1.4/LibHunterPetInfo-v1.4-classic.zip

    - name: 'TBC'
      install:
        - export GAME_VERSION="bcc"
        - git clone https://github.com/Gethe/wow-ui-source tests/wow-ui-source -b classic_beta
        - wget -q -O LibHunterPetInfo.zip https://github.com/Beast-Masters-addons/LibHunterPetInfo/releases/download/v1.4/LibHunterPetInfo-v1.4-bc.zip

script:
  - mkdir .release
  - unzip LibHunterPetInfo.zip -d .release/GFW_HuntersHelper
  - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -g $GAME_VERSION -o
